// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/block.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeader struct {
	Version              *uint32    `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Height               *uint32    `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	Time                 *int64     `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	Nounce               *uint32    `protobuf:"varint,4,req,name=nounce" json:"nounce,omitempty"`
	Difficulty           *uint32    `protobuf:"varint,5,req,name=difficulty" json:"difficulty,omitempty"`
	Prev                 *Hash      `protobuf:"bytes,6,req,name=prev" json:"prev,omitempty"`
	TxRoot               *Hash      `protobuf:"bytes,7,req,name=txRoot" json:"txRoot,omitempty"`
	Status               *Hash      `protobuf:"bytes,8,req,name=status" json:"status,omitempty"`
	Sign                 *Signature `protobuf:"bytes,9,opt,name=sign" json:"sign,omitempty"`
	Data                 []byte     `protobuf:"bytes,10,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_1d89ca8c5d88f532, []int{0}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *BlockHeader) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockHeader) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *BlockHeader) GetNounce() uint32 {
	if m != nil && m.Nounce != nil {
		return *m.Nounce
	}
	return 0
}

func (m *BlockHeader) GetDifficulty() uint32 {
	if m != nil && m.Difficulty != nil {
		return *m.Difficulty
	}
	return 0
}

func (m *BlockHeader) GetPrev() *Hash {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *BlockHeader) GetTxRoot() *Hash {
	if m != nil {
		return m.TxRoot
	}
	return nil
}

func (m *BlockHeader) GetStatus() *Hash {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BlockHeader) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *BlockHeader) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Block struct {
	Header               *BlockHeader  `protobuf:"bytes,1,req,name=header" json:"header,omitempty"`
	TxList               *Transactions `protobuf:"bytes,2,opt,name=txList" json:"txList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_1d89ca8c5d88f532, []int{1}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTxList() *Transactions {
	if m != nil {
		return m.TxList
	}
	return nil
}

type Blocks struct {
	Block                []*Block `protobuf:"bytes,1,rep,name=block" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Blocks) Reset()         { *m = Blocks{} }
func (m *Blocks) String() string { return proto.CompactTextString(m) }
func (*Blocks) ProtoMessage()    {}
func (*Blocks) Descriptor() ([]byte, []int) {
	return fileDescriptor_block_1d89ca8c5d88f532, []int{2}
}
func (m *Blocks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blocks.Unmarshal(m, b)
}
func (m *Blocks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blocks.Marshal(b, m, deterministic)
}
func (dst *Blocks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blocks.Merge(dst, src)
}
func (m *Blocks) XXX_Size() int {
	return xxx_messageInfo_Blocks.Size(m)
}
func (m *Blocks) XXX_DiscardUnknown() {
	xxx_messageInfo_Blocks.DiscardUnknown(m)
}

var xxx_messageInfo_Blocks proto.InternalMessageInfo

func (m *Blocks) GetBlock() []*Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "protobuf.BlockHeader")
	proto.RegisterType((*Block)(nil), "protobuf.Block")
	proto.RegisterType((*Blocks)(nil), "protobuf.Blocks")
}

func init() { proto.RegisterFile("protobuf/block.proto", fileDescriptor_block_1d89ca8c5d88f532) }

var fileDescriptor_block_1d89ca8c5d88f532 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x95, 0x34, 0x4d, 0xfb, 0x4f, 0x7e, 0x40, 0x32, 0x50, 0x8d, 0xba, 0x40, 0x51, 0x24,
	0x20, 0x1b, 0x52, 0x29, 0x47, 0x60, 0xd5, 0x05, 0x2b, 0xc3, 0x05, 0xdc, 0xd4, 0x69, 0x2d, 0x8a,
	0x5d, 0xc5, 0x93, 0x0a, 0xee, 0xc6, 0xe1, 0x90, 0x9d, 0x94, 0x54, 0xa8, 0x3b, 0xbf, 0x79, 0x5f,
	0x66, 0x32, 0x6f, 0xe0, 0x66, 0xdf, 0x18, 0x32, 0xab, 0xb6, 0x5e, 0xac, 0x76, 0xa6, 0x7a, 0x2f,
	0xbc, 0x64, 0xd3, 0x63, 0x75, 0x3e, 0xff, 0xf5, 0xa9, 0x11, 0xda, 0x8a, 0x8a, 0x94, 0xd1, 0x1d,
	0x95, 0x7d, 0x87, 0x90, 0x3c, 0xbb, 0xaf, 0x96, 0x52, 0xac, 0x65, 0xc3, 0x10, 0x26, 0x07, 0xd9,
	0x58, 0x65, 0x34, 0x06, 0x69, 0x98, 0x5f, 0xf0, 0xa3, 0x64, 0x33, 0x88, 0xb7, 0x52, 0x6d, 0xb6,
	0x84, 0xa1, 0x37, 0x7a, 0xc5, 0x18, 0x44, 0xa4, 0x3e, 0x24, 0x8e, 0xd2, 0x30, 0x1f, 0x71, 0xff,
	0x76, 0xac, 0x36, 0xad, 0xae, 0x24, 0x46, 0x1d, 0xdb, 0x29, 0x76, 0x07, 0xb0, 0x56, 0x75, 0xad,
	0xaa, 0x76, 0x47, 0x5f, 0x38, 0xf6, 0xde, 0x49, 0x85, 0x65, 0x10, 0xed, 0x1b, 0x79, 0xc0, 0x38,
	0x0d, 0xf3, 0xa4, 0xbc, 0x2c, 0x8e, 0x3f, 0x5e, 0x2c, 0x85, 0xdd, 0x72, 0xef, 0xb1, 0x07, 0x88,
	0xe9, 0x93, 0x1b, 0x43, 0x38, 0x39, 0x4b, 0xf5, 0xae, 0xe3, 0x2c, 0x09, 0x6a, 0x2d, 0x4e, 0xcf,
	0x73, 0x9d, 0xcb, 0x1e, 0x21, 0xb2, 0x6a, 0xa3, 0xf1, 0x5f, 0x1a, 0xe4, 0x49, 0x79, 0x3d, 0x50,
	0xaf, 0x6a, 0xa3, 0x05, 0xb5, 0x8d, 0xe4, 0x1e, 0x70, 0x8b, 0xae, 0x05, 0x09, 0x84, 0x34, 0xc8,
	0xff, 0x73, 0xff, 0xce, 0x6a, 0x18, 0xfb, 0xf4, 0xd8, 0x93, 0x4b, 0xc7, 0x25, 0xe8, 0x63, 0x4b,
	0xca, 0xdb, 0xa1, 0xcf, 0x49, 0xbc, 0xbc, 0x87, 0x58, 0xe1, 0x96, 0x78, 0x51, 0xd6, 0x85, 0xe9,
	0xc6, 0xce, 0x06, 0xfc, 0x6d, 0xb8, 0x91, 0xe5, 0x3d, 0x95, 0x2d, 0x20, 0xf6, 0x6d, 0x2c, 0xbb,
	0x87, 0xb1, 0xbf, 0x32, 0x06, 0xe9, 0x28, 0x4f, 0xca, 0xab, 0x3f, 0x73, 0x78, 0xe7, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x6a, 0x99, 0x36, 0xd6, 0x14, 0x02, 0x00, 0x00,
}
