// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/contract.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BlockHeaderData struct {
	ReceiptHash          *Hash    `protobuf:"bytes,1,req,name=receiptHash" json:"receiptHash,omitempty"`
	GasLimit             *uint64  `protobuf:"varint,2,req,name=gasLimit" json:"gasLimit,omitempty"`
	GasUsed              *uint64  `protobuf:"varint,3,req,name=gasUsed" json:"gasUsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeaderData) Reset()         { *m = BlockHeaderData{} }
func (m *BlockHeaderData) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderData) ProtoMessage()    {}
func (*BlockHeaderData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afd3d30283bce23, []int{0}
}

func (m *BlockHeaderData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderData.Unmarshal(m, b)
}
func (m *BlockHeaderData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderData.Marshal(b, m, deterministic)
}
func (m *BlockHeaderData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderData.Merge(m, src)
}
func (m *BlockHeaderData) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderData.Size(m)
}
func (m *BlockHeaderData) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderData.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderData proto.InternalMessageInfo

func (m *BlockHeaderData) GetReceiptHash() *Hash {
	if m != nil {
		return m.ReceiptHash
	}
	return nil
}

func (m *BlockHeaderData) GetGasLimit() uint64 {
	if m != nil && m.GasLimit != nil {
		return *m.GasLimit
	}
	return 0
}

func (m *BlockHeaderData) GetGasUsed() uint64 {
	if m != nil && m.GasUsed != nil {
		return *m.GasUsed
	}
	return 0
}

type TxData struct {
	Price                *uint64  `protobuf:"varint,1,req,name=price" json:"price,omitempty"`
	GasLimit             *uint64  `protobuf:"varint,2,req,name=gasLimit" json:"gasLimit,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,req,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxData) Reset()         { *m = TxData{} }
func (m *TxData) String() string { return proto.CompactTextString(m) }
func (*TxData) ProtoMessage()    {}
func (*TxData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afd3d30283bce23, []int{1}
}

func (m *TxData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxData.Unmarshal(m, b)
}
func (m *TxData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxData.Marshal(b, m, deterministic)
}
func (m *TxData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxData.Merge(m, src)
}
func (m *TxData) XXX_Size() int {
	return xxx_messageInfo_TxData.Size(m)
}
func (m *TxData) XXX_DiscardUnknown() {
	xxx_messageInfo_TxData.DiscardUnknown(m)
}

var xxx_messageInfo_TxData proto.InternalMessageInfo

func (m *TxData) GetPrice() uint64 {
	if m != nil && m.Price != nil {
		return *m.Price
	}
	return 0
}

func (m *TxData) GetGasLimit() uint64 {
	if m != nil && m.GasLimit != nil {
		return *m.GasLimit
	}
	return 0
}

func (m *TxData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Receipt struct {
	PostStateOrStatus    []byte   `protobuf:"bytes,1,req,name=postStateOrStatus" json:"postStateOrStatus,omitempty"`
	CumulativeGasUsed    *uint64  `protobuf:"varint,2,req,name=cumulativeGasUsed" json:"cumulativeGasUsed,omitempty"`
	Bloom                []byte   `protobuf:"bytes,3,req,name=bloom" json:"bloom,omitempty"`
	Logs                 []*Log   `protobuf:"bytes,4,rep,name=logs" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afd3d30283bce23, []int{2}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetPostStateOrStatus() []byte {
	if m != nil {
		return m.PostStateOrStatus
	}
	return nil
}

func (m *Receipt) GetCumulativeGasUsed() uint64 {
	if m != nil && m.CumulativeGasUsed != nil {
		return *m.CumulativeGasUsed
	}
	return 0
}

func (m *Receipt) GetBloom() []byte {
	if m != nil {
		return m.Bloom
	}
	return nil
}

func (m *Receipt) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

type Log struct {
	Address              *AccountID `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Topics               []*Hash    `protobuf:"bytes,2,rep,name=topics" json:"topics,omitempty"`
	Data                 []byte     `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afd3d30283bce23, []int{3}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetAddress() *AccountID {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Log) GetTopics() []*Hash {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *Log) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ReceiptForStorage struct {
	PostStateOrStatus    []byte           `protobuf:"bytes,1,req,name=postStateOrStatus" json:"postStateOrStatus,omitempty"`
	CumulativeGasUsed    *uint64          `protobuf:"varint,2,req,name=cumulativeGasUsed" json:"cumulativeGasUsed,omitempty"`
	Bloom                []byte           `protobuf:"bytes,3,req,name=bloom" json:"bloom,omitempty"`
	Logs                 []*LogForStorage `protobuf:"bytes,4,rep,name=logs" json:"logs,omitempty"`
	TxHash               *Hash            `protobuf:"bytes,5,req,name=txHash" json:"txHash,omitempty"`
	GasUsed              *uint64          `protobuf:"varint,6,req,name=gasUsed" json:"gasUsed,omitempty"`
	ContractAddress      *AccountID       `protobuf:"bytes,7,req,name=ContractAddress" json:"ContractAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReceiptForStorage) Reset()         { *m = ReceiptForStorage{} }
func (m *ReceiptForStorage) String() string { return proto.CompactTextString(m) }
func (*ReceiptForStorage) ProtoMessage()    {}
func (*ReceiptForStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afd3d30283bce23, []int{4}
}

func (m *ReceiptForStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptForStorage.Unmarshal(m, b)
}
func (m *ReceiptForStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptForStorage.Marshal(b, m, deterministic)
}
func (m *ReceiptForStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptForStorage.Merge(m, src)
}
func (m *ReceiptForStorage) XXX_Size() int {
	return xxx_messageInfo_ReceiptForStorage.Size(m)
}
func (m *ReceiptForStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptForStorage.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptForStorage proto.InternalMessageInfo

func (m *ReceiptForStorage) GetPostStateOrStatus() []byte {
	if m != nil {
		return m.PostStateOrStatus
	}
	return nil
}

func (m *ReceiptForStorage) GetCumulativeGasUsed() uint64 {
	if m != nil && m.CumulativeGasUsed != nil {
		return *m.CumulativeGasUsed
	}
	return 0
}

func (m *ReceiptForStorage) GetBloom() []byte {
	if m != nil {
		return m.Bloom
	}
	return nil
}

func (m *ReceiptForStorage) GetLogs() []*LogForStorage {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *ReceiptForStorage) GetTxHash() *Hash {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *ReceiptForStorage) GetGasUsed() uint64 {
	if m != nil && m.GasUsed != nil {
		return *m.GasUsed
	}
	return 0
}

func (m *ReceiptForStorage) GetContractAddress() *AccountID {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

type ReceiptForStorages struct {
	Receipts             []*ReceiptForStorage `protobuf:"bytes,1,rep,name=receipts" json:"receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ReceiptForStorages) Reset()         { *m = ReceiptForStorages{} }
func (m *ReceiptForStorages) String() string { return proto.CompactTextString(m) }
func (*ReceiptForStorages) ProtoMessage()    {}
func (*ReceiptForStorages) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afd3d30283bce23, []int{5}
}

func (m *ReceiptForStorages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiptForStorages.Unmarshal(m, b)
}
func (m *ReceiptForStorages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiptForStorages.Marshal(b, m, deterministic)
}
func (m *ReceiptForStorages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptForStorages.Merge(m, src)
}
func (m *ReceiptForStorages) XXX_Size() int {
	return xxx_messageInfo_ReceiptForStorages.Size(m)
}
func (m *ReceiptForStorages) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptForStorages.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptForStorages proto.InternalMessageInfo

func (m *ReceiptForStorages) GetReceipts() []*ReceiptForStorage {
	if m != nil {
		return m.Receipts
	}
	return nil
}

type LogForStorage struct {
	Address              *AccountID `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Topics               []*Hash    `protobuf:"bytes,2,rep,name=topics" json:"topics,omitempty"`
	Data                 []byte     `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	BlockNumber          *uint64    `protobuf:"varint,4,req,name=blockNumber" json:"blockNumber,omitempty"`
	TxHash               *Hash      `protobuf:"bytes,5,req,name=txHash" json:"txHash,omitempty"`
	TxIndex              *uint32    `protobuf:"varint,6,req,name=txIndex" json:"txIndex,omitempty"`
	BlockHash            *Hash      `protobuf:"bytes,7,req,name=blockHash" json:"blockHash,omitempty"`
	Index                *uint32    `protobuf:"varint,8,req,name=index" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LogForStorage) Reset()         { *m = LogForStorage{} }
func (m *LogForStorage) String() string { return proto.CompactTextString(m) }
func (*LogForStorage) ProtoMessage()    {}
func (*LogForStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0afd3d30283bce23, []int{6}
}

func (m *LogForStorage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogForStorage.Unmarshal(m, b)
}
func (m *LogForStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogForStorage.Marshal(b, m, deterministic)
}
func (m *LogForStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogForStorage.Merge(m, src)
}
func (m *LogForStorage) XXX_Size() int {
	return xxx_messageInfo_LogForStorage.Size(m)
}
func (m *LogForStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogForStorage.DiscardUnknown(m)
}

var xxx_messageInfo_LogForStorage proto.InternalMessageInfo

func (m *LogForStorage) GetAddress() *AccountID {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *LogForStorage) GetTopics() []*Hash {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *LogForStorage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LogForStorage) GetBlockNumber() uint64 {
	if m != nil && m.BlockNumber != nil {
		return *m.BlockNumber
	}
	return 0
}

func (m *LogForStorage) GetTxHash() *Hash {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *LogForStorage) GetTxIndex() uint32 {
	if m != nil && m.TxIndex != nil {
		return *m.TxIndex
	}
	return 0
}

func (m *LogForStorage) GetBlockHash() *Hash {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *LogForStorage) GetIndex() uint32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*BlockHeaderData)(nil), "protobuf.BlockHeaderData")
	proto.RegisterType((*TxData)(nil), "protobuf.TxData")
	proto.RegisterType((*Receipt)(nil), "protobuf.Receipt")
	proto.RegisterType((*Log)(nil), "protobuf.Log")
	proto.RegisterType((*ReceiptForStorage)(nil), "protobuf.ReceiptForStorage")
	proto.RegisterType((*ReceiptForStorages)(nil), "protobuf.ReceiptForStorages")
	proto.RegisterType((*LogForStorage)(nil), "protobuf.LogForStorage")
}

func init() { proto.RegisterFile("protobuf/contract.proto", fileDescriptor_0afd3d30283bce23) }

var fileDescriptor_0afd3d30283bce23 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x55, 0xc7, 0x8d, 0xc3, 0xa4, 0xa1, 0xea, 0x82, 0x54, 0x2b, 0x5c, 0x82, 0x0f, 0x28,
	0x12, 0x25, 0xa0, 0x5e, 0x38, 0x71, 0x28, 0x54, 0xd0, 0x4a, 0x01, 0xa4, 0x6d, 0x79, 0x80, 0xc9,
	0x7a, 0x31, 0x16, 0x8e, 0xd7, 0xda, 0x1d, 0xa3, 0xf4, 0x65, 0x38, 0xf0, 0x0a, 0xbc, 0x20, 0xf2,
	0xee, 0x3a, 0x4e, 0x9a, 0x22, 0xc4, 0x05, 0x4e, 0xc9, 0xec, 0xfc, 0xfa, 0x67, 0xf6, 0xf3, 0xbf,
	0x70, 0x5c, 0x69, 0x45, 0x6a, 0x51, 0x7f, 0x7e, 0x2e, 0x54, 0x49, 0x1a, 0x05, 0xcd, 0xec, 0x09,
	0x1b, 0xb4, 0x8d, 0xf1, 0x78, 0x2d, 0x21, 0x8d, 0xa5, 0x41, 0x41, 0xb9, 0x2a, 0x9d, 0x2a, 0xb9,
	0x81, 0xc3, 0xd7, 0x85, 0x12, 0x5f, 0x2f, 0x24, 0xa6, 0x52, 0x9f, 0x23, 0x21, 0x7b, 0x01, 0x43,
	0x2d, 0x85, 0xcc, 0x2b, 0xba, 0x40, 0xf3, 0x25, 0xde, 0x9b, 0x04, 0xd3, 0xe1, 0xe9, 0xfd, 0x59,
	0x6b, 0x32, 0x6b, 0x4e, 0xf9, 0xa6, 0x84, 0x8d, 0x61, 0x90, 0xa1, 0x99, 0xe7, 0xcb, 0x9c, 0xe2,
	0x60, 0x12, 0x4c, 0x43, 0xbe, 0xae, 0x59, 0x0c, 0x51, 0x86, 0xe6, 0x93, 0x91, 0x69, 0xdc, 0xb3,
	0xad, 0xb6, 0x4c, 0xae, 0xa1, 0x7f, 0xbd, 0xb2, 0x13, 0x1f, 0xc2, 0x7e, 0xa5, 0x73, 0x21, 0xed,
	0xac, 0x90, 0xbb, 0xe2, 0x4f, 0xae, 0x15, 0xde, 0x14, 0x0a, 0x9d, 0xeb, 0x01, 0x6f, 0xcb, 0xe4,
	0xfb, 0x1e, 0x44, 0xdc, 0xed, 0xc6, 0x4e, 0xe0, 0xa8, 0x52, 0x86, 0xae, 0x08, 0x49, 0x7e, 0xd4,
	0xcd, 0x4f, 0x6d, 0xec, 0x8c, 0x03, 0xbe, 0xdb, 0x68, 0xd4, 0xa2, 0x5e, 0xd6, 0x05, 0x52, 0xfe,
	0x4d, 0xbe, 0xf3, 0x3b, 0xbb, 0xc1, 0xbb, 0x8d, 0x66, 0xe7, 0x45, 0xa1, 0xd4, 0xd2, 0xcf, 0x77,
	0x05, 0x7b, 0x0c, 0x61, 0xa1, 0x32, 0x13, 0x87, 0x93, 0xde, 0x74, 0x78, 0x3a, 0xea, 0xa0, 0xcd,
	0x55, 0xc6, 0x6d, 0x2b, 0xa9, 0xa0, 0x37, 0x57, 0x19, 0x7b, 0x06, 0x11, 0xa6, 0xa9, 0x96, 0xc6,
	0x78, 0xc2, 0x0f, 0x3a, 0xf1, 0x99, 0x10, 0xaa, 0x2e, 0xe9, 0xf2, 0x9c, 0xb7, 0x1a, 0xf6, 0x04,
	0xfa, 0xa4, 0xaa, 0x5c, 0x98, 0x38, 0xb0, 0xd6, 0xb7, 0xbf, 0x87, 0xef, 0x32, 0x06, 0x61, 0x8a,
	0x84, 0x7e, 0x2b, 0xfb, 0x3f, 0xf9, 0x19, 0xc0, 0x91, 0x47, 0xf2, 0x56, 0xe9, 0x2b, 0x52, 0x1a,
	0x33, 0xf9, 0x1f, 0xe0, 0x3c, 0xdd, 0x82, 0x73, 0xbc, 0x05, 0xa7, 0x5b, 0xcc, 0x61, 0xb2, 0x17,
	0x5e, 0xd9, 0x00, 0xee, 0xdf, 0x19, 0x40, 0xdf, 0xdd, 0xcc, 0x57, 0x7f, 0x2b, 0x5f, 0xec, 0x15,
	0x1c, 0xbe, 0xf1, 0x4f, 0xe2, 0xcc, 0x93, 0x8e, 0x7e, 0x4f, 0xfa, 0xb6, 0x36, 0x79, 0x0f, 0x6c,
	0x07, 0x9a, 0x61, 0x2f, 0x61, 0xe0, 0x93, 0xdf, 0xc0, 0x6a, 0xee, 0xf1, 0xa8, 0x73, 0xdb, 0xd1,
	0xf3, 0xb5, 0x38, 0xf9, 0x11, 0xc0, 0x68, 0xeb, 0x9e, 0xff, 0x30, 0x01, 0x6c, 0x02, 0xc3, 0x45,
	0xf3, 0xca, 0x3f, 0xd4, 0xcb, 0x85, 0xd4, 0x71, 0x68, 0x41, 0x6d, 0x1e, 0xfd, 0x0d, 0x6e, 0x5a,
	0x5d, 0x96, 0xa9, 0x5c, 0x59, 0xdc, 0x23, 0xde, 0x96, 0xec, 0x04, 0xee, 0x59, 0x43, 0x6b, 0x12,
	0xdd, 0x69, 0xd2, 0x09, 0x9a, 0x84, 0xe4, 0xd6, 0x65, 0x60, 0x5d, 0x5c, 0xf1, 0x2b, 0x00, 0x00,
	0xff, 0xff, 0x7b, 0xed, 0xde, 0xd1, 0xcd, 0x04, 0x00, 0x00,
}
