// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/protobufmsg.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusData struct {
	ProtocolVersion      *uint32  `protobuf:"varint,1,req,name=protocolVersion" json:"protocolVersion,omitempty"`
	NetworkId            *uint64  `protobuf:"varint,2,req,name=networkId" json:"networkId,omitempty"`
	CurrentBlock         *Hash    `protobuf:"bytes,3,req,name=currentBlock" json:"currentBlock,omitempty"`
	GenesisBlock         *Hash    `protobuf:"bytes,4,req,name=genesisBlock" json:"genesisBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusData) Reset()         { *m = StatusData{} }
func (m *StatusData) String() string { return proto.CompactTextString(m) }
func (*StatusData) ProtoMessage()    {}
func (*StatusData) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_c5b714c0538c8346, []int{0}
}
func (m *StatusData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusData.Unmarshal(m, b)
}
func (m *StatusData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusData.Marshal(b, m, deterministic)
}
func (dst *StatusData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusData.Merge(dst, src)
}
func (m *StatusData) XXX_Size() int {
	return xxx_messageInfo_StatusData.Size(m)
}
func (m *StatusData) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusData.DiscardUnknown(m)
}

var xxx_messageInfo_StatusData proto.InternalMessageInfo

func (m *StatusData) GetProtocolVersion() uint32 {
	if m != nil && m.ProtocolVersion != nil {
		return *m.ProtocolVersion
	}
	return 0
}

func (m *StatusData) GetNetworkId() uint64 {
	if m != nil && m.NetworkId != nil {
		return *m.NetworkId
	}
	return 0
}

func (m *StatusData) GetCurrentBlock() *Hash {
	if m != nil {
		return m.CurrentBlock
	}
	return nil
}

func (m *StatusData) GetGenesisBlock() *Hash {
	if m != nil {
		return m.GenesisBlock
	}
	return nil
}

type NewBlockHashData struct {
	Hash                 *Hash    `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	Number               *uint64  `protobuf:"varint,2,req,name=number" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBlockHashData) Reset()         { *m = NewBlockHashData{} }
func (m *NewBlockHashData) String() string { return proto.CompactTextString(m) }
func (*NewBlockHashData) ProtoMessage()    {}
func (*NewBlockHashData) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_c5b714c0538c8346, []int{1}
}
func (m *NewBlockHashData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlockHashData.Unmarshal(m, b)
}
func (m *NewBlockHashData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlockHashData.Marshal(b, m, deterministic)
}
func (dst *NewBlockHashData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlockHashData.Merge(dst, src)
}
func (m *NewBlockHashData) XXX_Size() int {
	return xxx_messageInfo_NewBlockHashData.Size(m)
}
func (m *NewBlockHashData) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlockHashData.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlockHashData proto.InternalMessageInfo

func (m *NewBlockHashData) GetHash() *Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *NewBlockHashData) GetNumber() uint64 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

type NewBlockHashesDatas struct {
	Data                 []*NewBlockHashData `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NewBlockHashesDatas) Reset()         { *m = NewBlockHashesDatas{} }
func (m *NewBlockHashesDatas) String() string { return proto.CompactTextString(m) }
func (*NewBlockHashesDatas) ProtoMessage()    {}
func (*NewBlockHashesDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_c5b714c0538c8346, []int{2}
}
func (m *NewBlockHashesDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlockHashesDatas.Unmarshal(m, b)
}
func (m *NewBlockHashesDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlockHashesDatas.Marshal(b, m, deterministic)
}
func (dst *NewBlockHashesDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlockHashesDatas.Merge(dst, src)
}
func (m *NewBlockHashesDatas) XXX_Size() int {
	return xxx_messageInfo_NewBlockHashesDatas.Size(m)
}
func (m *NewBlockHashesDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlockHashesDatas.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlockHashesDatas proto.InternalMessageInfo

func (m *NewBlockHashesDatas) GetData() []*NewBlockHashData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockHeadersData struct {
	Hash                 *Hash    `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	Number               *uint64  `protobuf:"varint,2,req,name=number" json:"number,omitempty"`
	Amount               *uint64  `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	Skip                 *uint64  `protobuf:"varint,4,req,name=skip" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeadersData) Reset()         { *m = GetBlockHeadersData{} }
func (m *GetBlockHeadersData) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeadersData) ProtoMessage()    {}
func (*GetBlockHeadersData) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_c5b714c0538c8346, []int{3}
}
func (m *GetBlockHeadersData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeadersData.Unmarshal(m, b)
}
func (m *GetBlockHeadersData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeadersData.Marshal(b, m, deterministic)
}
func (dst *GetBlockHeadersData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeadersData.Merge(dst, src)
}
func (m *GetBlockHeadersData) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeadersData.Size(m)
}
func (m *GetBlockHeadersData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeadersData.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeadersData proto.InternalMessageInfo

func (m *GetBlockHeadersData) GetHash() *Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *GetBlockHeadersData) GetNumber() uint64 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *GetBlockHeadersData) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *GetBlockHeadersData) GetSkip() uint64 {
	if m != nil && m.Skip != nil {
		return *m.Skip
	}
	return 0
}

type Msg struct {
	Code                 *uint64  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_c5b714c0538c8346, []int{4}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (dst *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(dst, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetCode() uint64 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Msg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Cap struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Version              *uint64  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cap) Reset()         { *m = Cap{} }
func (m *Cap) String() string { return proto.CompactTextString(m) }
func (*Cap) ProtoMessage()    {}
func (*Cap) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_c5b714c0538c8346, []int{5}
}
func (m *Cap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cap.Unmarshal(m, b)
}
func (m *Cap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cap.Marshal(b, m, deterministic)
}
func (dst *Cap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cap.Merge(dst, src)
}
func (m *Cap) XXX_Size() int {
	return xxx_messageInfo_Cap.Size(m)
}
func (m *Cap) XXX_DiscardUnknown() {
	xxx_messageInfo_Cap.DiscardUnknown(m)
}

var xxx_messageInfo_Cap proto.InternalMessageInfo

func (m *Cap) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Cap) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type ProtoHandshake struct {
	Version              *uint64  `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Caps                 []*Cap   `protobuf:"bytes,3,rep,name=caps" json:"caps,omitempty"`
	ListenPort           *uint64  `protobuf:"varint,4,opt,name=listenPort" json:"listenPort,omitempty"`
	Id                   []byte   `protobuf:"bytes,5,opt,name=id" json:"id,omitempty"`
	Rest                 []byte   `protobuf:"bytes,6,opt,name=rest" json:"rest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoHandshake) Reset()         { *m = ProtoHandshake{} }
func (m *ProtoHandshake) String() string { return proto.CompactTextString(m) }
func (*ProtoHandshake) ProtoMessage()    {}
func (*ProtoHandshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_c5b714c0538c8346, []int{6}
}
func (m *ProtoHandshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoHandshake.Unmarshal(m, b)
}
func (m *ProtoHandshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoHandshake.Marshal(b, m, deterministic)
}
func (dst *ProtoHandshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoHandshake.Merge(dst, src)
}
func (m *ProtoHandshake) XXX_Size() int {
	return xxx_messageInfo_ProtoHandshake.Size(m)
}
func (m *ProtoHandshake) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoHandshake.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoHandshake proto.InternalMessageInfo

func (m *ProtoHandshake) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *ProtoHandshake) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProtoHandshake) GetCaps() []*Cap {
	if m != nil {
		return m.Caps
	}
	return nil
}

func (m *ProtoHandshake) GetListenPort() uint64 {
	if m != nil && m.ListenPort != nil {
		return *m.ListenPort
	}
	return 0
}

func (m *ProtoHandshake) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ProtoHandshake) GetRest() []byte {
	if m != nil {
		return m.Rest
	}
	return nil
}

func init() {
	proto.RegisterType((*StatusData)(nil), "protobuf.StatusData")
	proto.RegisterType((*NewBlockHashData)(nil), "protobuf.NewBlockHashData")
	proto.RegisterType((*NewBlockHashesDatas)(nil), "protobuf.NewBlockHashesDatas")
	proto.RegisterType((*GetBlockHeadersData)(nil), "protobuf.GetBlockHeadersData")
	proto.RegisterType((*Msg)(nil), "protobuf.Msg")
	proto.RegisterType((*Cap)(nil), "protobuf.Cap")
	proto.RegisterType((*ProtoHandshake)(nil), "protobuf.ProtoHandshake")
}

func init() {
	proto.RegisterFile("protobuf/protobufmsg.proto", fileDescriptor_protobufmsg_c5b714c0538c8346)
}

var fileDescriptor_protobufmsg_c5b714c0538c8346 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0xa5, 0xd0, 0x69, 0x1b, 0xd0, 0x56, 0x42, 0xab, 0x08, 0x21, 0xe3, 0x93, 0x4f,
	0x41, 0x0a, 0x7f, 0x40, 0x41, 0x84, 0x03, 0x55, 0xb5, 0x48, 0xdc, 0xa7, 0xf6, 0x92, 0x58, 0x49,
	0x76, 0xad, 0x9d, 0x35, 0x15, 0x07, 0x3e, 0x87, 0xbf, 0xe0, 0xe3, 0xd0, 0x8e, 0x6d, 0xec, 0x04,
	0x6e, 0xdc, 0xde, 0xbc, 0x79, 0x6f, 0x76, 0xe6, 0xd9, 0xb0, 0x68, 0xbc, 0x0b, 0xee, 0xbe, 0xfd,
	0xfa, 0x7a, 0x00, 0x07, 0xda, 0x2c, 0x19, 0xcb, 0x27, 0x03, 0xb5, 0x18, 0x55, 0xc1, 0xa3, 0x25,
	0x2c, 0x43, 0xed, 0x6c, 0xa7, 0xca, 0x7f, 0x25, 0x00, 0x9f, 0x03, 0x86, 0x96, 0xde, 0x61, 0x40,
	0x59, 0xc0, 0x53, 0xe6, 0x4b, 0xb7, 0xff, 0x62, 0x3c, 0xd5, 0xce, 0xaa, 0x24, 0x4b, 0x8b, 0x2b,
	0x7d, 0x4a, 0xcb, 0x17, 0x70, 0x6e, 0x4d, 0x78, 0x70, 0x7e, 0xf7, 0xb1, 0x52, 0x69, 0x96, 0x16,
	0x42, 0x8f, 0x84, 0x5c, 0xc1, 0x65, 0xd9, 0x7a, 0x6f, 0x6c, 0x78, 0xbb, 0x77, 0xe5, 0x4e, 0xcd,
	0xb2, 0xb4, 0xb8, 0x58, 0xcd, 0x97, 0xc3, 0x26, 0xcb, 0x35, 0xd2, 0x56, 0x1f, 0x69, 0xa2, 0x67,
	0x63, 0xac, 0xa1, 0x9a, 0x3a, 0x8f, 0xf8, 0xb7, 0x67, 0xaa, 0xc9, 0x6f, 0xe1, 0xd9, 0xad, 0x79,
	0x60, 0x1c, 0xbb, 0x7c, 0x43, 0x0e, 0x62, 0x8b, 0xb4, 0xe5, 0xc5, 0xff, 0xf6, 0x73, 0x4f, 0x3e,
	0x87, 0x33, 0xdb, 0x1e, 0xee, 0x8d, 0xef, 0x57, 0xef, 0xab, 0xfc, 0x3d, 0x5c, 0x4f, 0xe7, 0x19,
	0x4e, 0x85, 0xe4, 0x12, 0x44, 0x85, 0x01, 0x55, 0x92, 0xcd, 0x8a, 0x8b, 0xd5, 0x62, 0x1c, 0x79,
	0xfa, 0xb8, 0x66, 0x5d, 0xfe, 0x03, 0xae, 0x3f, 0x98, 0xee, 0xac, 0xb5, 0xc1, 0xca, 0x78, 0xfa,
	0xdf, 0xcd, 0x22, 0x8f, 0x07, 0xd7, 0xda, 0xc0, 0x59, 0x0a, 0xdd, 0x57, 0x52, 0x82, 0xa0, 0x5d,
	0xdd, 0x70, 0x5a, 0x42, 0x33, 0xce, 0xdf, 0xc0, 0xec, 0x13, 0x6d, 0x62, 0xab, 0x74, 0x95, 0xe1,
	0xe7, 0x84, 0x66, 0x2c, 0x15, 0x3c, 0x6e, 0xf0, 0xfb, 0xde, 0x61, 0xfc, 0x68, 0x49, 0x71, 0xa9,
	0x87, 0x32, 0x9a, 0x6e, 0xb0, 0x89, 0x26, 0x8b, 0x87, 0xce, 0x74, 0xae, 0x19, 0x47, 0xd3, 0xb7,
	0xfe, 0x6f, 0xe8, 0x96, 0x1a, 0xca, 0xfc, 0x67, 0x02, 0xf3, 0xbb, 0x78, 0xc5, 0x1a, 0x6d, 0x45,
	0x5b, 0xdc, 0x1d, 0x89, 0x93, 0x23, 0xf1, 0x9f, 0xd1, 0xe9, 0x64, 0xf4, 0x2b, 0x10, 0x25, 0x36,
	0xa4, 0x66, 0x9c, 0xec, 0xd5, 0x18, 0xc9, 0x0d, 0x36, 0x9a, 0x5b, 0xf2, 0x25, 0xc0, 0xbe, 0xa6,
	0x60, 0xec, 0x9d, 0xf3, 0x41, 0x89, 0x2c, 0x29, 0x84, 0x9e, 0x30, 0x72, 0x0e, 0x69, 0x5d, 0xa9,
	0x47, 0x7c, 0x4d, 0x5a, 0x57, 0xf1, 0x19, 0x6f, 0x28, 0xa8, 0x33, 0x66, 0x18, 0xff, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x95, 0x52, 0x9c, 0x59, 0x29, 0x03, 0x00, 0x00,
}
