// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/trie.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HashNode struct {
	Data                 []byte   `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashNode) Reset()         { *m = HashNode{} }
func (m *HashNode) String() string { return proto.CompactTextString(m) }
func (*HashNode) ProtoMessage()    {}
func (*HashNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_77173f6eb0822a18, []int{0}
}

func (m *HashNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashNode.Unmarshal(m, b)
}
func (m *HashNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashNode.Marshal(b, m, deterministic)
}
func (m *HashNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashNode.Merge(m, src)
}
func (m *HashNode) XXX_Size() int {
	return xxx_messageInfo_HashNode.Size(m)
}
func (m *HashNode) XXX_DiscardUnknown() {
	xxx_messageInfo_HashNode.DiscardUnknown(m)
}

var xxx_messageInfo_HashNode proto.InternalMessageInfo

func (m *HashNode) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ValueNode struct {
	Data                 []byte   `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValueNode) Reset()         { *m = ValueNode{} }
func (m *ValueNode) String() string { return proto.CompactTextString(m) }
func (*ValueNode) ProtoMessage()    {}
func (*ValueNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_77173f6eb0822a18, []int{1}
}

func (m *ValueNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueNode.Unmarshal(m, b)
}
func (m *ValueNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueNode.Marshal(b, m, deterministic)
}
func (m *ValueNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueNode.Merge(m, src)
}
func (m *ValueNode) XXX_Size() int {
	return xxx_messageInfo_ValueNode.Size(m)
}
func (m *ValueNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueNode.DiscardUnknown(m)
}

var xxx_messageInfo_ValueNode proto.InternalMessageInfo

func (m *ValueNode) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*HashNode)(nil), "protobuf.HashNode")
	proto.RegisterType((*ValueNode)(nil), "protobuf.ValueNode")
}

func init() { proto.RegisterFile("protobuf/trie.proto", fileDescriptor_77173f6eb0822a18) }

var fileDescriptor_77173f6eb0822a18 = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x29, 0xca, 0x4c, 0xd5, 0x03, 0xf3, 0x84, 0x38, 0x60, 0x82,
	0x4a, 0x72, 0x5c, 0x1c, 0x1e, 0x89, 0xc5, 0x19, 0x7e, 0xf9, 0x29, 0xa9, 0x42, 0x42, 0x5c, 0x2c,
	0x29, 0x89, 0x25, 0x89, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x3c, 0x17,
	0x67, 0x58, 0x62, 0x4e, 0x69, 0x2a, 0x2e, 0x05, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0x54,
	0x0a, 0x18, 0x60, 0x00, 0x00, 0x00,
}
