// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobufmsg.proto

package protobufmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Msg struct {
	Code                 *uint64  `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}
func (*Msg) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_e04f5ead7f14986a, []int{0}
}
func (m *Msg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Msg.Unmarshal(m, b)
}
func (m *Msg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Msg.Marshal(b, m, deterministic)
}
func (dst *Msg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Msg.Merge(dst, src)
}
func (m *Msg) XXX_Size() int {
	return xxx_messageInfo_Msg.Size(m)
}
func (m *Msg) XXX_DiscardUnknown() {
	xxx_messageInfo_Msg.DiscardUnknown(m)
}

var xxx_messageInfo_Msg proto.InternalMessageInfo

func (m *Msg) GetCode() uint64 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Msg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Cap struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Version              *uint64  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cap) Reset()         { *m = Cap{} }
func (m *Cap) String() string { return proto.CompactTextString(m) }
func (*Cap) ProtoMessage()    {}
func (*Cap) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_e04f5ead7f14986a, []int{1}
}
func (m *Cap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cap.Unmarshal(m, b)
}
func (m *Cap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cap.Marshal(b, m, deterministic)
}
func (dst *Cap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cap.Merge(dst, src)
}
func (m *Cap) XXX_Size() int {
	return xxx_messageInfo_Cap.Size(m)
}
func (m *Cap) XXX_DiscardUnknown() {
	xxx_messageInfo_Cap.DiscardUnknown(m)
}

var xxx_messageInfo_Cap proto.InternalMessageInfo

func (m *Cap) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Cap) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type ProtoHandshake struct {
	Version              *uint64  `protobuf:"varint,1,req,name=version" json:"version,omitempty"`
	Name                 *string  `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Caps                 []*Cap   `protobuf:"bytes,3,rep,name=caps" json:"caps,omitempty"`
	ListenPort           *uint64  `protobuf:"varint,4,opt,name=listenPort" json:"listenPort,omitempty"`
	Id                   []byte   `protobuf:"bytes,5,opt,name=id" json:"id,omitempty"`
	Rest                 []byte   `protobuf:"bytes,6,opt,name=rest" json:"rest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoHandshake) Reset()         { *m = ProtoHandshake{} }
func (m *ProtoHandshake) String() string { return proto.CompactTextString(m) }
func (*ProtoHandshake) ProtoMessage()    {}
func (*ProtoHandshake) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_e04f5ead7f14986a, []int{2}
}
func (m *ProtoHandshake) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoHandshake.Unmarshal(m, b)
}
func (m *ProtoHandshake) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoHandshake.Marshal(b, m, deterministic)
}
func (dst *ProtoHandshake) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoHandshake.Merge(dst, src)
}
func (m *ProtoHandshake) XXX_Size() int {
	return xxx_messageInfo_ProtoHandshake.Size(m)
}
func (m *ProtoHandshake) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoHandshake.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoHandshake proto.InternalMessageInfo

func (m *ProtoHandshake) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *ProtoHandshake) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ProtoHandshake) GetCaps() []*Cap {
	if m != nil {
		return m.Caps
	}
	return nil
}

func (m *ProtoHandshake) GetListenPort() uint64 {
	if m != nil && m.ListenPort != nil {
		return *m.ListenPort
	}
	return 0
}

func (m *ProtoHandshake) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ProtoHandshake) GetRest() []byte {
	if m != nil {
		return m.Rest
	}
	return nil
}

func init() {
	proto.RegisterType((*Msg)(nil), "protobufmsg.Msg")
	proto.RegisterType((*Cap)(nil), "protobufmsg.Cap")
	proto.RegisterType((*ProtoHandshake)(nil), "protobufmsg.ProtoHandshake")
}

func init() { proto.RegisterFile("protobufmsg.proto", fileDescriptor_protobufmsg_e04f5ead7f14986a) }

var fileDescriptor_protobufmsg_e04f5ead7f14986a = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x4a, 0x83, 0x31,
	0x10, 0x85, 0x49, 0xfe, 0xa8, 0x38, 0x95, 0xa2, 0x59, 0xcd, 0x4a, 0x7e, 0x8a, 0x8b, 0xac, 0xba,
	0xd0, 0x23, 0x74, 0xe3, 0x46, 0x28, 0xb9, 0xc1, 0xd8, 0xc4, 0x1a, 0x6c, 0x93, 0x90, 0x44, 0xc1,
	0x1b, 0x79, 0x4c, 0xc9, 0x48, 0x25, 0xdd, 0xbd, 0x79, 0x33, 0xdf, 0x1b, 0x1e, 0xdc, 0xe5, 0x92,
	0x5a, 0x7a, 0xfd, 0x7c, 0x3b, 0xd6, 0xfd, 0x9a, 0xb5, 0x5e, 0x0c, 0xd6, 0xea, 0x09, 0xa6, 0x97,
	0xba, 0xd7, 0x1a, 0xd4, 0x2e, 0x39, 0x8f, 0x62, 0x96, 0x46, 0x59, 0xd6, 0x1a, 0xe1, 0x2a, 0xd3,
	0xf7, 0x21, 0x91, 0x43, 0x39, 0x0b, 0x73, 0x63, 0x4f, 0x63, 0x87, 0x36, 0x94, 0x3b, 0x14, 0xe9,
	0xf8, 0x07, 0x5d, 0x5b, 0xd6, 0x1d, 0xfa, 0xf2, 0xa5, 0x86, 0x14, 0x51, 0x72, 0xd6, 0x69, 0x5c,
	0xfd, 0x08, 0x58, 0x6e, 0xfb, 0xe7, 0x67, 0x8a, 0xae, 0xbe, 0xd3, 0xc7, 0xd9, 0xb1, 0x38, 0x3b,
	0xfe, 0x8f, 0x96, 0x43, 0xf4, 0x03, 0xa8, 0x1d, 0xe5, 0x8a, 0xd3, 0x3c, 0x99, 0xc5, 0xe3, 0xed,
	0x7a, 0x6c, 0xb6, 0xa1, 0x6c, 0x79, 0xab, 0xef, 0x01, 0x0e, 0xa1, 0x36, 0x1f, 0xb7, 0xa9, 0x34,
	0x54, 0xb3, 0x30, 0xca, 0x0e, 0x8e, 0x5e, 0x82, 0x0c, 0x0e, 0x2f, 0xb8, 0x90, 0x0c, 0xae, 0x7f,
	0x2a, 0xbe, 0x36, 0xbc, 0x64, 0x87, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xfd, 0xea,
	0x1d, 0x35, 0x01, 0x00, 0x00,
}
