// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobufmsg.proto

package protobufmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hash struct {
	Data                 []byte   `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hash) Reset()         { *m = Hash{} }
func (m *Hash) String() string { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()    {}
func (*Hash) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_ac3350bd1516b0b3, []int{0}
}
func (m *Hash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hash.Unmarshal(m, b)
}
func (m *Hash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hash.Marshal(b, m, deterministic)
}
func (dst *Hash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hash.Merge(dst, src)
}
func (m *Hash) XXX_Size() int {
	return xxx_messageInfo_Hash.Size(m)
}
func (m *Hash) XXX_DiscardUnknown() {
	xxx_messageInfo_Hash.DiscardUnknown(m)
}

var xxx_messageInfo_Hash proto.InternalMessageInfo

func (m *Hash) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StatusData struct {
	ProtocolVersion      *uint32  `protobuf:"varint,1,req,name=protocolVersion" json:"protocolVersion,omitempty"`
	NetworkId            *uint64  `protobuf:"varint,2,req,name=networkId" json:"networkId,omitempty"`
	Td                   *int64   `protobuf:"varint,3,req,name=td" json:"td,omitempty"`
	CurrentBlock         *Hash    `protobuf:"bytes,4,req,name=currentBlock" json:"currentBlock,omitempty"`
	GenesisBlock         *Hash    `protobuf:"bytes,5,req,name=genesisBlock" json:"genesisBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusData) Reset()         { *m = StatusData{} }
func (m *StatusData) String() string { return proto.CompactTextString(m) }
func (*StatusData) ProtoMessage()    {}
func (*StatusData) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_ac3350bd1516b0b3, []int{1}
}
func (m *StatusData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusData.Unmarshal(m, b)
}
func (m *StatusData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusData.Marshal(b, m, deterministic)
}
func (dst *StatusData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusData.Merge(dst, src)
}
func (m *StatusData) XXX_Size() int {
	return xxx_messageInfo_StatusData.Size(m)
}
func (m *StatusData) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusData.DiscardUnknown(m)
}

var xxx_messageInfo_StatusData proto.InternalMessageInfo

func (m *StatusData) GetProtocolVersion() uint32 {
	if m != nil && m.ProtocolVersion != nil {
		return *m.ProtocolVersion
	}
	return 0
}

func (m *StatusData) GetNetworkId() uint64 {
	if m != nil && m.NetworkId != nil {
		return *m.NetworkId
	}
	return 0
}

func (m *StatusData) GetTd() int64 {
	if m != nil && m.Td != nil {
		return *m.Td
	}
	return 0
}

func (m *StatusData) GetCurrentBlock() *Hash {
	if m != nil {
		return m.CurrentBlock
	}
	return nil
}

func (m *StatusData) GetGenesisBlock() *Hash {
	if m != nil {
		return m.GenesisBlock
	}
	return nil
}

type NewBlockHashData struct {
	Hash                 *Hash    `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	Number               *uint64  `protobuf:"varint,2,req,name=number" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewBlockHashData) Reset()         { *m = NewBlockHashData{} }
func (m *NewBlockHashData) String() string { return proto.CompactTextString(m) }
func (*NewBlockHashData) ProtoMessage()    {}
func (*NewBlockHashData) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_ac3350bd1516b0b3, []int{2}
}
func (m *NewBlockHashData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlockHashData.Unmarshal(m, b)
}
func (m *NewBlockHashData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlockHashData.Marshal(b, m, deterministic)
}
func (dst *NewBlockHashData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlockHashData.Merge(dst, src)
}
func (m *NewBlockHashData) XXX_Size() int {
	return xxx_messageInfo_NewBlockHashData.Size(m)
}
func (m *NewBlockHashData) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlockHashData.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlockHashData proto.InternalMessageInfo

func (m *NewBlockHashData) GetHash() *Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *NewBlockHashData) GetNumber() uint64 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

type NewBlockHashesDatas struct {
	Data                 []*NewBlockHashData `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NewBlockHashesDatas) Reset()         { *m = NewBlockHashesDatas{} }
func (m *NewBlockHashesDatas) String() string { return proto.CompactTextString(m) }
func (*NewBlockHashesDatas) ProtoMessage()    {}
func (*NewBlockHashesDatas) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_ac3350bd1516b0b3, []int{3}
}
func (m *NewBlockHashesDatas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewBlockHashesDatas.Unmarshal(m, b)
}
func (m *NewBlockHashesDatas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewBlockHashesDatas.Marshal(b, m, deterministic)
}
func (dst *NewBlockHashesDatas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewBlockHashesDatas.Merge(dst, src)
}
func (m *NewBlockHashesDatas) XXX_Size() int {
	return xxx_messageInfo_NewBlockHashesDatas.Size(m)
}
func (m *NewBlockHashesDatas) XXX_DiscardUnknown() {
	xxx_messageInfo_NewBlockHashesDatas.DiscardUnknown(m)
}

var xxx_messageInfo_NewBlockHashesDatas proto.InternalMessageInfo

func (m *NewBlockHashesDatas) GetData() []*NewBlockHashData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBlockHeadersData struct {
	Hash                 *Hash    `protobuf:"bytes,1,req,name=hash" json:"hash,omitempty"`
	Number               *uint64  `protobuf:"varint,2,req,name=number" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeadersData) Reset()         { *m = GetBlockHeadersData{} }
func (m *GetBlockHeadersData) String() string { return proto.CompactTextString(m) }
func (*GetBlockHeadersData) ProtoMessage()    {}
func (*GetBlockHeadersData) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_ac3350bd1516b0b3, []int{4}
}
func (m *GetBlockHeadersData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockHeadersData.Unmarshal(m, b)
}
func (m *GetBlockHeadersData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockHeadersData.Marshal(b, m, deterministic)
}
func (dst *GetBlockHeadersData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeadersData.Merge(dst, src)
}
func (m *GetBlockHeadersData) XXX_Size() int {
	return xxx_messageInfo_GetBlockHeadersData.Size(m)
}
func (m *GetBlockHeadersData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeadersData.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeadersData proto.InternalMessageInfo

func (m *GetBlockHeadersData) GetHash() *Hash {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *GetBlockHeadersData) GetNumber() uint64 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*Hash)(nil), "protobufmsg.Hash")
	proto.RegisterType((*StatusData)(nil), "protobufmsg.StatusData")
	proto.RegisterType((*NewBlockHashData)(nil), "protobufmsg.NewBlockHashData")
	proto.RegisterType((*NewBlockHashesDatas)(nil), "protobufmsg.NewBlockHashesDatas")
	proto.RegisterType((*GetBlockHeadersData)(nil), "protobufmsg.GetBlockHeadersData")
}

func init() { proto.RegisterFile("protobufmsg.proto", fileDescriptor_protobufmsg_ac3350bd1516b0b3) }

var fileDescriptor_protobufmsg_ac3350bd1516b0b3 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x50, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0x65, 0x69, 0x14, 0xbc, 0x9d, 0x1f, 0xcb, 0x40, 0x8a, 0x28, 0x94, 0x82, 0x90, 0xa7, 0x81,
	0x03, 0xff, 0x80, 0x08, 0xd6, 0x17, 0xc1, 0x28, 0xbe, 0x67, 0xcd, 0x75, 0x1d, 0xdb, 0x12, 0x49,
	0x52, 0xf6, 0x3f, 0xfd, 0x45, 0xd2, 0xbb, 0xa2, 0xdd, 0xd0, 0x37, 0xdf, 0x6e, 0x4e, 0xce, 0x39,
	0x9c, 0x73, 0x60, 0xf4, 0xe1, 0x5d, 0x74, 0xb3, 0xe6, 0x7d, 0x1d, 0xe6, 0x13, 0xba, 0x45, 0xda,
	0x83, 0x8a, 0x0b, 0xe0, 0xa5, 0x0e, 0xb5, 0x10, 0xc0, 0x8d, 0x8e, 0x3a, 0x1b, 0xe4, 0x4c, 0x0e,
	0x15, 0xdd, 0xc5, 0xe7, 0x00, 0xe0, 0x25, 0xea, 0xd8, 0x84, 0x7b, 0x1d, 0xb5, 0x90, 0x70, 0x4a,
	0xca, 0xca, 0xad, 0xde, 0xd0, 0x87, 0x85, 0xb3, 0xc4, 0x3e, 0x56, 0xfb, 0xb0, 0xb8, 0x84, 0x23,
	0x8b, 0x71, 0xe3, 0xfc, 0xf2, 0xd1, 0x64, 0x2c, 0x67, 0x92, 0xab, 0x1f, 0x40, 0x9c, 0x00, 0x8b,
	0x26, 0x4b, 0x72, 0x26, 0x13, 0xc5, 0xa2, 0x11, 0xb7, 0x30, 0xac, 0x1a, 0xef, 0xd1, 0xc6, 0xbb,
	0x95, 0xab, 0x96, 0x19, 0xcf, 0x99, 0x4c, 0xa7, 0xa3, 0x49, 0x3f, 0x79, 0x9b, 0x51, 0xed, 0xd0,
	0x5a, 0xd9, 0x1c, 0x2d, 0x86, 0x45, 0xd8, 0xca, 0x0e, 0xfe, 0x94, 0xf5, 0x69, 0xc5, 0x33, 0x9c,
	0x3d, 0xe1, 0x86, 0xee, 0xf6, 0x97, 0x9a, 0x5d, 0x03, 0xaf, 0x75, 0xa8, 0xa9, 0xce, 0xaf, 0x16,
	0xf4, 0x2d, 0xce, 0xe1, 0xd0, 0x36, 0xeb, 0x19, 0xfa, 0xae, 0x53, 0xf7, 0x2a, 0x4a, 0x18, 0xf7,
	0x2d, 0x91, 0xe6, 0x0a, 0xe2, 0xe6, 0x7b, 0xd2, 0x44, 0xa6, 0xd3, 0xab, 0x1d, 0xd7, 0xfd, 0x08,
	0xdd, 0xe2, 0xaf, 0x30, 0x7e, 0xc0, 0x6d, 0xbf, 0x12, 0xb5, 0x41, 0x1f, 0xfe, 0x21, 0xdf, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x41, 0x4c, 0xf1, 0x4d, 0x04, 0x02, 0x00, 0x00,
}
