// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobufmsg.proto

package protobufmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hash struct {
	Data                 []byte   `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hash) Reset()         { *m = Hash{} }
func (m *Hash) String() string { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()    {}
func (*Hash) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_d367ee9b15d72cc8, []int{0}
}
func (m *Hash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hash.Unmarshal(m, b)
}
func (m *Hash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hash.Marshal(b, m, deterministic)
}
func (dst *Hash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hash.Merge(dst, src)
}
func (m *Hash) XXX_Size() int {
	return xxx_messageInfo_Hash.Size(m)
}
func (m *Hash) XXX_DiscardUnknown() {
	xxx_messageInfo_Hash.DiscardUnknown(m)
}

var xxx_messageInfo_Hash proto.InternalMessageInfo

func (m *Hash) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type StatusData struct {
	ProtocolVersion      *uint32  `protobuf:"varint,1,req,name=protocolVersion" json:"protocolVersion,omitempty"`
	NetworkId            *uint64  `protobuf:"varint,2,req,name=networkId" json:"networkId,omitempty"`
	Td                   *int64   `protobuf:"varint,3,req,name=td" json:"td,omitempty"`
	CurrentBlock         *Hash    `protobuf:"bytes,4,req,name=currentBlock" json:"currentBlock,omitempty"`
	GenesisBlock         *Hash    `protobuf:"bytes,5,req,name=genesisBlock" json:"genesisBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusData) Reset()         { *m = StatusData{} }
func (m *StatusData) String() string { return proto.CompactTextString(m) }
func (*StatusData) ProtoMessage()    {}
func (*StatusData) Descriptor() ([]byte, []int) {
	return fileDescriptor_protobufmsg_d367ee9b15d72cc8, []int{1}
}
func (m *StatusData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusData.Unmarshal(m, b)
}
func (m *StatusData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusData.Marshal(b, m, deterministic)
}
func (dst *StatusData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusData.Merge(dst, src)
}
func (m *StatusData) XXX_Size() int {
	return xxx_messageInfo_StatusData.Size(m)
}
func (m *StatusData) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusData.DiscardUnknown(m)
}

var xxx_messageInfo_StatusData proto.InternalMessageInfo

func (m *StatusData) GetProtocolVersion() uint32 {
	if m != nil && m.ProtocolVersion != nil {
		return *m.ProtocolVersion
	}
	return 0
}

func (m *StatusData) GetNetworkId() uint64 {
	if m != nil && m.NetworkId != nil {
		return *m.NetworkId
	}
	return 0
}

func (m *StatusData) GetTd() int64 {
	if m != nil && m.Td != nil {
		return *m.Td
	}
	return 0
}

func (m *StatusData) GetCurrentBlock() *Hash {
	if m != nil {
		return m.CurrentBlock
	}
	return nil
}

func (m *StatusData) GetGenesisBlock() *Hash {
	if m != nil {
		return m.GenesisBlock
	}
	return nil
}

func init() {
	proto.RegisterType((*Hash)(nil), "protobufmsg.Hash")
	proto.RegisterType((*StatusData)(nil), "protobufmsg.StatusData")
}

func init() { proto.RegisterFile("protobufmsg.proto", fileDescriptor_protobufmsg_d367ee9b15d72cc8) }

var fileDescriptor_protobufmsg_d367ee9b15d72cc8 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xcb, 0x2d, 0x4e, 0xd7, 0x03, 0xb3, 0x85, 0xb8, 0x91, 0x84, 0x94, 0xa4,
	0xb8, 0x58, 0x3c, 0x12, 0x8b, 0x33, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18,
	0x15, 0x98, 0x34, 0x78, 0x82, 0xc0, 0x6c, 0xa5, 0x4b, 0x8c, 0x5c, 0x5c, 0xc1, 0x25, 0x89, 0x25,
	0xa5, 0xc5, 0x2e, 0x89, 0x25, 0x89, 0x42, 0x1a, 0x5c, 0xfc, 0x60, 0x9d, 0xc9, 0xf9, 0x39, 0x61,
	0xa9, 0x45, 0xc5, 0x99, 0xf9, 0x79, 0x60, 0xd5, 0xbc, 0x41, 0xe8, 0xc2, 0x42, 0x32, 0x5c, 0x9c,
	0x79, 0xa9, 0x25, 0xe5, 0xf9, 0x45, 0xd9, 0x9e, 0x29, 0x12, 0x4c, 0x0a, 0x4c, 0x1a, 0x2c, 0x41,
	0x08, 0x01, 0x21, 0x3e, 0x2e, 0xa6, 0x92, 0x14, 0x09, 0x66, 0x05, 0x26, 0x0d, 0xe6, 0x20, 0xa6,
	0x92, 0x14, 0x21, 0x53, 0x2e, 0x9e, 0xe4, 0xd2, 0xa2, 0xa2, 0xd4, 0xbc, 0x12, 0xa7, 0x9c, 0xfc,
	0xe4, 0x6c, 0x09, 0x16, 0x05, 0x26, 0x0d, 0x6e, 0x23, 0x41, 0x3d, 0x64, 0x97, 0x83, 0xdc, 0x18,
	0x84, 0xa2, 0x0c, 0xa4, 0x2d, 0x3d, 0x35, 0x2f, 0xb5, 0x38, 0xb3, 0x18, 0xa2, 0x8d, 0x15, 0xa7,
	0x36, 0x64, 0x65, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x43, 0x0d, 0x3e, 0x11, 0x01, 0x00,
	0x00,
}
